# Generated by Django 6.0.7 on 2026-07-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.company')),
            ],
        ),
    ]
