# Generated by Django 6.0.7 on 2026-07-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
