# Generated by Django 6.0.7 on 2026-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
