# Generated by Django 6.0.7 on 2026-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Opt Out', 'Opt Out')], default='Active', max_length=20),
        ),
    ]
